name: Todoist Today
no_screen_padding: 'no'
dark_mode: 'no'
strategy: polling
polling_verb: get
polling_url: http://192.168.50.163:3000/api/todoist
refresh_interval: 15
id: 01a08c81-b3da-7692-a2f1-757b198c1deb
